plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
apply plugin: 'kotlin-android'

android {
    compileSdk 32

    defaultConfig {
        applicationId "com.zyyme.workdayalarmclock"
        minSdk 14
        targetSdk 32
        versionCode 100
        versionName "29.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            debuggable false
            zipAlignEnabled true
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            zipAlignEnabled true
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main {
            // Android列表文件中显示的jniLibs实际是libs
            jniLibs.srcDirs = ['libs']
        }
    }

    flavorDimensions "version"
    productFlavors {
        full {
            dimension "version"
            ndk {
                abiFilters "armeabi-v7a", "arm64-v8a"
            }
        }
        nolauncher {
            dimension "version"
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
        x86 {
            dimension "version"
            ndk {
                abiFilters "x86"
            }
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

def targetOutputDir = new File(rootDir, "app/release")

afterEvaluate {
    android.applicationVariants.all { variant ->
        def variantName = variant.name
        // 找到对应的 assemble 任务
        def assembleTask = variant.assembleProvider.get()

        if (assembleTask != null) {
            // 在 assemble 任务执行完成后触发复制
            assembleTask.doLast {
                copy {
                    // 从默认输出目录获取生成的文件
                    from variant.outputs*.outputFile
                    // 复制到指定的目标文件夹
                    into targetOutputDir
                }
                delete variant.outputs*.outputFile
            }
        }
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation "androidx.media:media:1.6.0"
}
